---
abstract: 'This class represents a single line from the Nginx combined access log (the default access log format). It may work with the combined Apache log too, but I have not tested this.'
author:
  - 'David Farrell <davidnmfarrell@gmail.com>'
build_requires:
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.64, CPAN::Meta::Converter version 2.130880'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Nginx-Log-Entry
no_index:
  directory:
    - t
    - inc
requires:
  Nginx::ParseLog: 1.01
  perl: 5.006
version: 0.02
